-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "ADMIN" SALT 'd47276c9f03c5f49' HASH '6f451e0d2b4107a6198ab383afabcddd18e13be9927782aeabdbbfa3ecd7dbef' ADMIN;      
CREATE SCHEMA IF NOT EXISTS "ORDERS" AUTHORIZATION "ADMIN";   
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" INTEGER NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(32) NOT NULL,
    "LAST_NAME" CHARACTER VARYING(32) NOT NULL,
    "PASSWORD" CHARACTER VARYING(64) NOT NULL,
    "ROLE" CHARACTER VARYING(16) DEFAULT 'customer' NOT NULL
);        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(0, 'admin', 'admin', 'password', 'CUSTOMER'),
(10, 'feras', 'a', 'password', 'CUSTOMER');              
CREATE CACHED TABLE "ORDERS"."SAVED"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "ITEMS" JSON NOT NULL,
    "ORDER_DATE" DATE NOT NULL,
    "CUSTOMER_ID" INTEGER
);  
ALTER TABLE "ORDERS"."SAVED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM ORDERS.SAVED;   
CREATE CACHED TABLE "ORDERS"."PENDING"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 347) NOT NULL,
    "ITEMS" JSON NOT NULL,
    "ORDER_DATE" DATE NOT NULL,
    "CUSTOMER_ID" INTEGER
);               
ALTER TABLE "ORDERS"."PENDING" ADD CONSTRAINT "ORDERS"."CONSTRAINT_2" PRIMARY KEY("ID");      
-- 123 +/- SELECT COUNT(*) FROM ORDERS.PENDING;               
INSERT INTO "ORDERS"."PENDING" VALUES
(7, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(8, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(9, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(10, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(11, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(12, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(13, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(14, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(15, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(16, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(17, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(18, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(19, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(20, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-07', 10),
(21, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(22, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(23, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(24, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10);              
INSERT INTO "ORDERS"."PENDING" VALUES
(25, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(26, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(27, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(28, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(29, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(30, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(31, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(32, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(33, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(34, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(35, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(36, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(37, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(38, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(39, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(40, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(41, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(42, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10);           
INSERT INTO "ORDERS"."PENDING" VALUES
(43, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(44, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(45, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(77, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(78, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(79, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(80, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(81, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(82, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(83, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(115, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(116, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(148, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(180, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(212, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(213, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(214, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(215, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10);   
INSERT INTO "ORDERS"."PENDING" VALUES
(216, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(217, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(218, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(250, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(251, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(252, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(253, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(254, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(255, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(256, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(257, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(258, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(259, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(260, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(261, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(262, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(263, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10);         
INSERT INTO "ORDERS"."PENDING" VALUES
(264, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(265, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(266, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(267, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(268, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(269, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(270, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(271, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(272, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-08', 10),
(273, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(274, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(275, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(276, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(277, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(278, JSON '"null,null"', DATE '2022-11-09', 10),
(279, JSON '"null,null"', DATE '2022-11-09', 10),
(280, JSON '"null,null"', DATE '2022-11-09', 10),
(281, JSON '"null,null"', DATE '2022-11-09', 10),
(282, JSON '"{\"size\":\"LARGE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"base\":\"CHEESE\"},{\"size\":\"SMALL\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"base\":\"VEGAN\"}"', DATE '2022-11-09', 10),
(283, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(284, JSON '"{\"base\":\"CHEESE\",\"size\":\"LARGE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"base\":\"VEGAN\",\"size\":\"SMALL\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10);               
INSERT INTO "ORDERS"."PENDING" VALUES
(285, JSON '"{\"base\":\"CHEESE\",\"size\":\"LARGE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"base\":\"VEGAN\",\"size\":\"SMALL\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(286, JSON '"{\"base\":\"CHEESE\",\"size\":\"LARGE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"base\":\"VEGAN\",\"size\":\"SMALL\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(287, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"jsonFields\":{\"size\":\"LARGE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"base\":\"CHEESE\"}},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"jsonFields\":{\"size\":\"SMALL\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"base\":\"VEGAN\"}}"', DATE '2022-11-09', 10),
(288, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"jsonFields\":{\"size\":\"LARGE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"base\":\"CHEESE\"}},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"jsonFields\":{\"size\":\"SMALL\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"base\":\"VEGAN\"}}"', DATE '2022-11-09', 10),
(289, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"jsonFields\":{\"size\":\"LARGE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"base\":\"CHEESE\"}},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"jsonFields\":{\"size\":\"SMALL\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"base\":\"VEGAN\"}}"', DATE '2022-11-09', 10),
(290, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"jsonFields\":{\"size\":\"LARGE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"base\":\"CHEESE\"}},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"jsonFields\":{\"size\":\"SMALL\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"base\":\"VEGAN\"}}"', DATE '2022-11-09', 10),
(291, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"jsonFields\":{\"size\":\"LARGE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"],\"base\":\"CHEESE\"}},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"jsonFields\":{\"size\":\"SMALL\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"],\"base\":\"VEGAN\"}}"', DATE '2022-11-09', 10),
(292, JSON '"{\"type\":\"PIZZA\",\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"type\":\"PIZZA\",\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(293, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(294, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(295, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(296, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(297, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(298, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(299, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10);    
INSERT INTO "ORDERS"."PENDING" VALUES
(300, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(301, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(302, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(303, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(304, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(305, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(306, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(307, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(308, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(309, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(310, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(311, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(312, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(313, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(314, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10),
(315, JSON '"{\"size\":\"LARGE\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\",\"ONIONS\"]},{\"size\":\"SMALL\",\"base\":\"VEGAN\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]}"', DATE '2022-11-09', 10);         
CREATE CACHED TABLE "ORDERS"."PROCESSED"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "ITEMS" JSON NOT NULL,
    "ORDER_DATE" DATE NOT NULL,
    "CUSTOMER_ID" INTEGER
);              
ALTER TABLE "ORDERS"."PROCESSED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_6" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM ORDERS.PROCESSED;               
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."VALID_ACCOUNT_TYPE" CHECK(LOWER("ROLE") IN('customer', 'customer service', 'chef')) NOCHECK;            
ALTER TABLE "ORDERS"."PENDING" ADD CONSTRAINT "ORDERS"."CONSTRAINT_21" UNIQUE("ID");          
ALTER TABLE "ORDERS"."SAVED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_4B" UNIQUE("ID");            
ALTER TABLE "ORDERS"."PROCESSED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_64" UNIQUE("ID");        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" UNIQUE("ID");            
ALTER TABLE "ORDERS"."PROCESSED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_64D" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;               
ALTER TABLE "ORDERS"."PENDING" ADD CONSTRAINT "ORDERS"."CONSTRAINT_21C" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK; 
ALTER TABLE "ORDERS"."SAVED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_4B0" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;   
