-- H2 2.1.214;
-- noinspection ALL
;              
CREATE USER IF NOT EXISTS "ADMIN" SALT 'd47276c9f03c5f49' HASH '6f451e0d2b4107a6198ab383afabcddd18e13be9927782aeabdbbfa3ecd7dbef' ADMIN;       
CREATE SCHEMA IF NOT EXISTS "ORDERS" AUTHORIZATION "ADMIN";    
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" INTEGER NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(32) NOT NULL,
    "LAST_NAME" CHARACTER VARYING(32) NOT NULL,
    "PASSWORD" CHARACTER VARYING(64) NOT NULL,
    "ROLE" CHARACTER VARYING(16) DEFAULT 'customer' NOT NULL
);               
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");         
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.USERS;    
INSERT INTO "PUBLIC"."USERS" VALUES
(0, 'admin', 'admin', 'password', 'CUSTOMER'),
(10, 'feras', 'a', 'password', 'CUSTOMER'),
(123, 'andrew', 'hudson', 'pass', 'CHEF');      
CREATE CACHED TABLE "ORDERS"."SAVED"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "ITEMS" JSON NOT NULL,
    "ORDER_DATE" DATE NOT NULL,
    "CUSTOMER_ID" INTEGER
);        
ALTER TABLE "ORDERS"."SAVED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_4" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM ORDERS.SAVED;    
CREATE CACHED TABLE "ORDERS"."PENDING"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 793) NOT NULL,
    "ITEMS" JSON NOT NULL,
    "ORDER_DATE" DATE NOT NULL,
    "CUSTOMER_ID" INTEGER
);     
ALTER TABLE "ORDERS"."PENDING" ADD CONSTRAINT "ORDERS"."CONSTRAINT_2" PRIMARY KEY("ID");       
-- 35 +/- SELECT COUNT(*) FROM ORDERS.PENDING; 
INSERT INTO "ORDERS"."PENDING" VALUES
(717, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(718, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(719, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(720, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(721, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(722, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(723, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(724, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(725, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(726, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(727, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(728, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(729, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(730, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(731, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10);
INSERT INTO "ORDERS"."PENDING" VALUES
(732, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(733, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(734, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(735, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(736, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(737, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(738, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(739, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(740, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(741, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(742, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(745, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(747, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(749, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(751, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10);            
INSERT INTO "ORDERS"."PENDING" VALUES
(783, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(785, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(787, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(789, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10),
(791, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":4,\"size\":\"MEDIUM\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":1,\"size\":\"XLARGE\",\"base\":\"CHEESE\",\"toppings\":[\"EXTRA_CHEESE\"]}]}"', DATE '2022-11-10', 10);          
CREATE CACHED TABLE "ORDERS"."PROCESSED"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "ITEMS" JSON NOT NULL,
    "ORDER_DATE" DATE NOT NULL,
    "CUSTOMER_ID" INTEGER
);    
ALTER TABLE "ORDERS"."PROCESSED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_6" PRIMARY KEY("ID");     
-- 5 +/- SELECT COUNT(*) FROM ORDERS.PROCESSED;
INSERT INTO "ORDERS"."PROCESSED" VALUES
(784, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(786, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(788, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(790, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10),
(792, JSON '"{\"items\":[{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"OLIVES\",\"PINEAPPLE\"]},{\"@class\":\"PIZZA\",\"quantity\":2,\"size\":\"SMALL\",\"base\":\"CHEESE\",\"toppings\":[\"MUSHROOMS\"]}]}"', DATE '2022-11-10', 10);               
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."VALID_ACCOUNT_TYPE" CHECK(LOWER("ROLE") IN('customer', 'customer service', 'chef')) NOCHECK;             
ALTER TABLE "ORDERS"."PENDING" ADD CONSTRAINT "ORDERS"."CONSTRAINT_21" UNIQUE("ID");           
ALTER TABLE "ORDERS"."SAVED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_4B" UNIQUE("ID");             
ALTER TABLE "ORDERS"."PROCESSED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_64" UNIQUE("ID");         
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" UNIQUE("ID");             
ALTER TABLE "ORDERS"."PROCESSED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_64D" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;
ALTER TABLE "ORDERS"."PENDING" ADD CONSTRAINT "ORDERS"."CONSTRAINT_21C" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;  
ALTER TABLE "ORDERS"."SAVED" ADD CONSTRAINT "ORDERS"."CONSTRAINT_4B0" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;    
